### ISSUE TITLE
Request: Official Typescript typings

### ISSUE THREAD

**Issue by Olian04** [hydrabolt/discord.js#1234]
Could we perhaps get some official typescript support?

**Comment by iCrawl** [comment]
Typings are already provided with the library.

**Comment by Olian04** [comment]
@iCrawl i found it, although i get this error `node_modules/discord.js/typings/index.d.ts(788,40): error TS2304: Cannot find name 'Map'.`. 
Think you could help me?

**Comment by Gawdl3y** [comment]
cc @zajrik

**Comment by zajrik** [comment]
`npm install --save @types/node` should fix it. Though its already a dependency of Discord.js so I'm not sure why you're having this issue.

**Comment by Olian04** [comment]
@zajrik I'm now using Typescript^2.2.1 and I've restarted the editor after updating, but I'm still getting the same error.

Worth noting is I'm running this command (from the terminal) when i get the error: `tsc ./app/*.ts --outDir ./dest/ -d true & node ./dest/index.js >> output.log`

**Comment by zajrik** [comment]
Oh, i can't actually speak for using tsc directly because I use gulp for all of my typescript compilation needs. Are you experiencing this error in your editor at all? That's where it really matters, to be honest. If it's not affecting your ability to write the code via errors then it's really as non-issue. Tsc is just really finnicky sometimes and the code will still compile regardless of missing typings.

**Comment by Olian04** [comment]
@zajrik 
Yea, i believe it works as it should in VScode.
Thanks anyway :)

**Comment by zajrik** [comment]
Alright, that's good. If you do have further problems with tsc I recommend giving gulp a try. You're welcome to snag the gulpfile from any of my typescript bot projects as a jumping off point. Though they're due for an update as I've since learned how to utilize my tsconfig with the gulp script and need to update accordingly.
