### ISSUE TITLE
messageReactionAdd doesn't work as expected in the master branch

### ISSUE THREAD

**Issue by SwadicalRag** [hydrabolt/discord.js#1269]
forewarning: okay, i spent like 2 hours figuring out why my reaction abstraction for my chat bot didn't work, and my head is aching

I'll keep it as concise as possible: 
**problem:** the "messageReactionAdd" isn't called
**probable cause:** (as a list of events that leads to the bug)
1. I send a message via the bot
2. I add three reactions to the message as the bot
3. I add a reaction to the bot using my own discord user account, which results in the bot editing the message
4. [the "messageUpdate" is called because of the message edit](https://github.com/hydrabolt/discord.js/blob/7232531eb1a60d89a3a5ce2ba660aee5ce17ac62/src/client/actions/MessageUpdate.js)
5. the message object is cloned, and Message.patch is called
6. Two fuck-ups here: 
 - [Message.patch(data)](https://github.com/hydrabolt/discord.js/blob/4ef0ec491c74612f38ca8b677ad6b1b1e59d576f/src/structures/Message.js#L182) clones the reaction list, but does not preserve the list of users that reacted
 - [encodeURIComponent isn't called ](https://github.com/hydrabolt/discord.js/blob/4ef0ec491c74612f38ca8b677ad6b1b1e59d576f/src/structures/Message.js#L238)for reaction.emoji.name (this also occurs in [the constructor](https://github.com/hydrabolt/discord.js/blob/4ef0ec491c74612f38ca8b677ad6b1b1e59d576f/src/structures/Message.js#L164))
7. I remove my reaction
8. [message._removeReaction is called](https://github.com/hydrabolt/discord.js/blob/f613cc3c500dfc527f1e6ccd7a04c4d121a01303/src/client/actions/MessageReactionRemove.js#L24)
9. The two fuck ups from before result in: 
 - discord.js not being able to find the reaction and failing at `if (this.reactions.has(emojiID)) {`
 - discord.js falsely concluding that a user hasn't previously reacted to a message and thus failing at `if (reaction.users.has(user.id)) {`
10. "messageReactionAdd" is no longer called.

**propsed solution:** can't make a pull request atm, but you'd have to somehow preserve the list of users of all reactions AND fix up the encodeURIComponent calls

**Comment by bdistin** [comment]
This should be fixed in my pr #1236 , if you have a moment can you try `npm i bdistin/discord.js` to insure that pr fixed all issues listed here? If it doesnt let me know, so i can fix any remaining issues.

**Comment by SwadicalRag** [comment]
after removing my detour of Message.patch and installing your fork of discord.js, the issue is still unresolved.

I'll go debug later today for you and see what's going wrong

for reference, here's my hacky runtime detour to solve the problem

```typescript
// !!! UNSAFE !!!
try {
    let oldPatch:Function = Discord.Message.prototype["patch"];

    let detouredPatch:(this: Discord.Message,data: any) => void = function(data) {
        let self = this;

        this.reactions["oldClear"] = this.reactions["oldClear"] || this.reactions.clear;

        let reactUsers = {};

        this.reactions.clear = function() {
            this.forEach((reaction,key) => {
                reactUsers[key] = reaction.users;
            });

            self.reactions["oldClear"].apply(this,[]);
        } as (this: Discord.Collection<string,Discord.MessageReaction>) => void;

        oldPatch.apply(this,[data]);

        this.reactions.clear = this.reactions["oldClear"];

        this.reactions.forEach((reaction,key) => {
            if(reactUsers[key]) {
                reaction.users = reactUsers[key];
            }
        });
    }

    Discord.Message.prototype["patch"] = detouredPatch;
}
catch(e) {
    io.error("discord detours failed: " + e.toString());
}
```
