### ISSUE TITLE
Possibly unhandled rejection at promise wrappedPromise

### ISSUE THREAD

**Issue by bonesoul** [hydrabolt/discord.js#1475]
```
Possibly unhandled rejection at promise wrappedPromise {
  <rejected> Error: Something took too long to do.
    at timeout.client.setTimeout (/var/www/buharmetre.com/node_modules/discord.js/src/client/ClientManager.js:40:57)
    at Timeout.setTimeout (/var/www/buharmetre.com/node_modules/discord.js/src/client/Client.js:422:7)
    at Timeout._onTimeout (/var/www/buharmetre.com/node_modules/async-listener/glue.js:188:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5),
  __asl_wrapper: [Function] }
```

my code is;

```
  try {
  await readDiscord();
 } catch (err) {
    return done(err);
 }

function readDiscord () {
  return new Promise((resolve, reject) => {
    try {
      let guildId = config.get('api.discord.guild');

      discord.on('ready', () => {
        if (!discord.guilds.has(guildId)) return resolve();
        let guild = discord.guilds.get(guildId);
        return resolve(guild.memberCount);
      });

      discord.login(config.get('api.discord.token'));
    } catch (err) {
      return reject(err);
    }
  });
}
```

**Comment by iCrawl** [comment]
I don't even know what this code is supposed to do, sorry. I also don't think this error is coming from the lib in this case.

**Comment by GusCaplan** [comment]
something took too long to do usually happens when the client takes too much time to log in, i would say this would be fixed by #1478 and you are providing an invalid token

**Comment by iCrawl** [comment]
Fixed in d11a658f and 79801871 respectively.

**Comment by cmakh** [comment]
Anyone else still encountering this error? I'm not getting it while logging in, but usually about 5 to 10 minutes after my bot has logged in. Before I get the error, the bot works perfectly fine, responds to commands, receives events, etc.
