### ISSUE TITLE
Typo causes crash.

### ISSUE THREAD

**Issue by tehkhop** [hydrabolt/discord.js#209]
lib/Client/InternalClient.js:1147

InternalClient::updateDetails();

if(!email) used instead of if(!this.email) for checking if token was used.

**Comment by Lord-Ptolemy** [comment]
https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1006
Already fixed in indev: 8d59498

**Comment by abalabahaha** [comment]
Duplicate of 8d59498 #176 #187 #203 #207 

Yes, NPM/master don't have this patch released yet. However, that still doesn't mean it isn't already fixed in development (indev branch).

**Comment by tehkhop** [comment]
Apologies.
