### ISSUE TITLE
setUsername() on userbots not working

### ISSUE THREAD

**Issue by Ckath** [hydrabolt/discord.js#700]
throws an error about email field required

**Comment by eslachance** [comment]
According to #697 , is fixed in fbcea236c53ab19bb74928933d0d144141403312 and available on indev.

**Comment by Ckath** [comment]
changed from the email field required to 'Password does not match', having used login with token

**Comment by hydrabolt** [comment]
Ok, as of https://github.com/hydrabolt/discord.js/commit/9308d2ead31edb12651fc1c2840945bcbf9fbdfe this is fixed, but you will still have to set the password when logging in with a token:
```js
client.login('token');
client.password = 'account password';
// ready to change username
```

Unfortunately, there's no way around this for user accounts and a password still has to be provided (which does make tokens a bit redundant for user accounts).

**Comment by iExit1337** [comment]
Still not working for me. Getting this error:
`message: 'Invalid Form Body\npassword: Password does not match.',
 code: 50035`
